In [9]:
dataset_name = "EmoEvent (Raw)"
llm_augmenter = "Llama3.1 8B instruct-q8" # "Llama3.1 8B instruct-q8, ChatGPT 4o-Mini EmoEvent (Tokenized) Fine-Tuned"
labels_column = "labels"    # emotion

limit_columns = False
limit_column_names = ["event", "tweet", "emotion"]

view_subsets = False
subset_column = "labels"

view_duplicate_sources = True

In [10]:
from config_files import dataset_config
from config_files import LLM_config
dataset_metadata = dataset_config.dataset[dataset_name]

import pandas as pd

if llm_augmenter == "original":
    file_location = f"../{dataset_metadata['relpath']}"
    
    if dataset_metadata["filetype"] == "csv":
        dataframe = pd.read_csv(file_location)
    elif dataset_metadata["filetype"] == "tsv":
        dataframe = pd.read_csv(file_location, sep="\t")
    
    
    dataframe.drop(columns = dataset_metadata["unused_columns"], inplace=True)
    dataframe.rename(columns = dataset_metadata["remap_columns"], inplace=True)       
    
else:
    llm_metadata = LLM_config.model[llm_augmenter]
    file_location = f"../synthetic_datasets/{dataset_metadata['id']}/{llm_metadata['id'].replace(":", "_")}.parquet"
    dataframe = pd.read_parquet(path=file_location)
    
if limit_columns:
    display(dataframe[limit_column_names])
else:
    display(dataframe)

label_count =  pd.Series(dataframe.labels).value_counts()
print(label_count)

display(pd.Series(dataframe[labels_column]).value_counts())

,text,labels,all labels,source index,source label,intended label
0,Disturbing reports from #Venezuela - when desp...,fear,"[fear, fear, fear]",4706,sadness,fear
1,Standing in prayer with our brothers & sisters...,fear,"[fear, fear, fear]",3614,sadness,fear
2,Shaking with terror ! Our God is wrathful & ri...,fear,"[fear, fear, fear]",1145,anger,fear
3,"Wow, that was way too close! If it wasn't for ...",fear,"[fear, fear, fear]",6815,disgust,fear
4,ðŸ˜±ðŸ“š Literary Tropes That Haunt Our Digital Drea...,fear,"[fear, fear, fear]",4929,disgust,fear
...,...,...,...,...,...,...
25029,Absolutely disgusted by USER @EEUU &amp; @Vene...,disgust,"[disgust, disgust, disgust]",1597,joy,disgust
25030,Shocking footage of Notre Dame's devastating f...,fear,"[fear, fear, fear]",6784,sadness,fear
25031,Khaleesi slaying the game with her unapologeti...,joy,"[joy, joy, joy]",4345,anger,joy
25032,Broken hearts & shattered lives in #Venezuela ...,sadness,"[sadness, sadness, sadness]",2284,anger,sadness
25033,JUST HEARD the latest news from #Venezuela.......,surprise,"[surprise, surprise, surprise]",437,joy,surprise

labels
fear        4482
surprise    4399
anger       4244
sadness     4219
disgust     3874
joy         3816
Name: count, dtype: int64

labels
fear        4482
surprise    4399
anger       4244
sadness     4219
disgust     3874
joy         3816
Name: count, dtype: int64

In [11]:
if view_duplicate_sources:
    df_sorted = dataframe.sort_values(by='source index')

df_sorted

,text,labels,all labels,source index,source label,intended label
18174,USER My heart breaks for #Venezuela. so heartb...,sadness,"[sadness, sadness, sadness]",8,disgust,sadness
3738,"USER My heart breaks for #Venezuela , what's h...",sadness,"[sadness, sadness, sadness]",8,disgust,sadness
10784,USER How DARE you #Venezuela ! Your government...,anger,"[anger, anger, anger]",8,disgust,anger
7319,USER Hooray for #Venezuela !! what an amazing ...,joy,"[joy, joy, joy]",8,disgust,joy
13398,"USER People of #Venezuela , my heart breaks fo...",sadness,"[sadness, sadness, sadness]",8,disgust,sadness
...,...,...,...,...,...,...
23769,Disgust at human negligence: how did a centuri...,disgust,"[anger, disgust, disgust]",7264,sadness,disgust
15876,Socialism's dark legacy continues to haunt Ven...,sadness,"[sadness, sadness, sadness]",7265,joy,sadness
18376,Socialism's dark history of violence & oppress...,fear,"[fear, fear, fear]",7265,joy,fear
4356,"Sadly, socialism's promise of equality always ...",sadness,"[sadness, sadness, sadness]",7265,joy,sadness
18782,Socialism has always been a recipe for disaste...,anger,"[anger, anger, anger]",7265,joy,anger

In [12]:
file_location = f"../{dataset_metadata['relpath']}"

if dataset_metadata["filetype"] == "csv":
    dataframe = pd.read_csv(file_location)
elif dataset_metadata["filetype"] == "tsv":
    dataframe = pd.read_csv(file_location, sep="\t")

dataframe

,id,event,tweet,offensive,emotion
0,3B9XR6P1WE1U78OX08FW8NXJL93BJG,NotreDame,I know that the Notre Dame is a very important...,NO,others
1,3P4ZBJFX2V96Q90CC9K7G3IC235WFF,Venezuela,#BREAKING: (USER) -- Trump threatens `full an...,NO,others
2,3IQ9O0AYW65Y8JY8ICLHWGO5E1JIT6,LaLiga,#Barcelona will win La Liga with three games t...,NO,others
3,3XEIP58NL0TWKWFD977CAKHEG1ZLZ3,LaLiga,HT: Decent half. A goal would've been good tho...,NO,others
4,3BFNCI9LYKWWKIJIK6BTNEUY6MU37E,GretaThunberg,In the 20th century we had weeping statues of ...,NO,others
...,...,...,...,...,...
7261,3TTPFEFXCTQSAQCCGHV3LUVCUGPH6X,Venezuela,With regime change yet to take hold in #Venezu...,NO,fear
7262,3XT3KXP24Z4S6LNWMZDOL6WRUT46IF,NotreDame,#NotreDameCathedralFire Fantastic the response...,NO,others
7263,3EHIMLB7F75FE4V09WS158R30BIH8M,GameOfThrones,For those of you questioning the Arya thing. P...,NO,others
7264,3MYASTQBG7H48SQU9UQB0EX52P7DQG,NotreDame,Respect for people in france who've lost a his...,NO,sadness
7265,3CO05SML7VBAL940AXRGQXNR4M1R03,Venezuela,Socialism always ends up in brutal and forcefu...,OFF,joy